# AUTOGENERATED! DO NOT EDIT! File to edit: ../media_campaign_cost.ipynb.

# %% auto 0
__all__ = ['comp', 'path']

# %% ../media_campaign_cost.ipynb 4
from fastai.tabular.all import *

# %% ../media_campaign_cost.ipynb 6
try: import fastkaggle
except ModuleNotFoundError:
    !pip install -Uq fastkaggle

from fastkaggle import *

# %% ../media_campaign_cost.ipynb 7
comp = 'playground-series-s3e11'
path = setup_comp(comp, install='fastai')
